import { StyleSheet } from "react-native";
import { PURPLE, DARK_MODAL_SURFACE } from "./constants";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f7f8fc" },
  container: { flex: 1 },
  content: { paddingHorizontal: 14, paddingTop: 8, paddingBottom: 110 },
  topBar: {
    height: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom: 6,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    overflow: "hidden",
  },
  topBarButton: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#eceef5",
  },
  topBarTitle: { alignItems: "center" },
  menuIcon: { color: "#1c2030", fontSize: 20, lineHeight: 22 },
  appName: { color: "#1c2030", fontSize: 16, fontWeight: "800" },
  appSubtitle: { color: "#8a8fa3", fontSize: 10, marginTop: 2 },
  eyebrow: { color: PURPLE, fontSize: 14, fontWeight: "600" },
  hero: {
    borderRadius: 21,
    padding: 21,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    overflow: "hidden",
    position: "relative",
  },
  reportToggle: {
    flexDirection: "row",
    backgroundColor: "#eef0f6",
    borderRadius: 12,
    padding: 3,
    marginBottom: 10,
  },
  reportToggleOption: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 9,
    borderRadius: 9,
  },
  reportToggleOptionActive: { backgroundColor: "#fff" },
  reportToggleText: { color: "#62677b", fontSize: 12, fontWeight: "700" },
  reportToggleTextActive: { color: PURPLE },
  reportPeriod: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eceef5",
    borderRadius: 13,
    paddingHorizontal: 4,
    marginBottom: 12,
  },
  reportArrowButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  reportPeriodText: { color: "#1c2030", fontSize: 14, fontWeight: "700" },
  reportHero: {
    minHeight: 142,
    padding: 19,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
    marginBottom: 10,
  },
  reportHeroOrb: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    right: -38,
    top: -38,
    backgroundColor: "#ffffff18",
  },
  reportHeroBubbleTwo: {
    position: "absolute",
    width: 82,
    height: 82,
    borderRadius: 41,
    right: 22,
    bottom: -45,
    backgroundColor: "#ffffff12",
  },
  reportHeroBubbleThree: {
    position: "absolute",
    width: 58,
    height: 58,
    borderRadius: 29,
    right: 112,
    top: 32,
    backgroundColor: "#ffffff1c",
  },
  reportHeroBubbleFour: {
    position: "absolute",
    width: 30,
    height: 30,
    borderRadius: 15,
    right: 92,
    bottom: 18,
    backgroundColor: "#ffffff2a",
  },
  reportHeroHint: { color: "#d9f4e4", fontSize: 13 },
  reportHeroTotal: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "800",
    marginVertical: 4,
  },
  reportHeroTrend: { color: "#d0efdc", fontSize: 11 },
  reportMetrics: { flexDirection: "row", gap: 8, marginBottom: 12 },
  reportMetric: {
    flex: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eceef5",
    borderRadius: 14,
    padding: 12,
  },
  reportMetricValue: {
    color: "#1c2030",
    fontSize: 15,
    fontWeight: "800",
    marginTop: 4,
  },
  reportChartContent: {
    minWidth: "100%",
    height: 174,
    alignItems: "flex-end",
    gap: 7,
    paddingTop: 22,
    paddingHorizontal: 4,
  },
  reportBarGroup: {
    width: 24,
    height: 150,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  reportYearBarGroup: { width: 48 },
  reportBar: { width: 16, backgroundColor: "#b7e3c7", borderRadius: 6 },
  reportChartValue: {
    color: "#62677b",
    fontSize: 8,
    fontWeight: "700",
    marginBottom: 4,
  },
  reportBarLabel: { color: "#8a8fa3", fontSize: 9, marginTop: 6 },
  reportYearBarLabel: {
    width: 48,
    textAlign: "center",
    fontSize: 8,
    includeFontPadding: false,
  },
  reportCategoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingVertical: 9,
    paddingHorizontal: 8,
  },
  reportCategoryRowActive: {
    backgroundColor: "#f7f8fc",
    borderRadius: 12,
  },
  reportCategoryIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#e5f4eb",
    fontSize: 17,
    textAlign: "center",
    textAlignVertical: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  reportCategoryInfo: { flex: 1, minWidth: 0 },
  reportCategoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  reportProgressTrack: {
    height: 6,
    backgroundColor: "#eef0f5",
    borderRadius: 6,
    overflow: "hidden",
    marginTop: 7,
  },
  reportProgressFill: { height: "100%", borderRadius: 6 },
  subBreakdown: {
    marginLeft: 43,
    marginBottom: 5,
    paddingLeft: 12,
    paddingVertical: 7,
    borderLeftWidth: 2,
    borderLeftColor: "#d9eee1",
  },
  subBreakdownTitle: {
    color: PURPLE,
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 3,
  },
  subBreakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 5,
    gap: 8,
  },
  subBreakdownName: { color: "#62677b", fontSize: 12, flex: 1 },
  subBreakdownAmount: { color: "#1c2030", fontSize: 12, fontWeight: "700" },
  glowOne: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#ffffff16",
    right: -22,
    top: -35,
  },
  glowTwo: {
    position: "absolute",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#ffffff12",
    right: 23,
    bottom: -55,
  },
  glowThree: {
    position: "absolute",
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#ffffff1c",
    right: 112,
    top: 37,
  },
  glowFour: {
    position: "absolute",
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ffffff2a",
    right: 105,
    bottom: 16,
  },
  glowFive: {
    position: "absolute",
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ffffff36",
    right: 78,
    top: 16,
  },
  heroShine: {
    position: "absolute",
    top: -45,
    width: 58,
    height: 220,
    backgroundColor: "#ffffff2b",
  },
  heroHint: { color: "#e0dcff", fontSize: 14 },
  heroTotal: {
    color: "#fff",
    fontSize: 34,
    fontWeight: "800",
    marginVertical: 2,
  },
  heroTrend: { color: "#dedaff", fontSize: 12 },
  heroOrb: {
    width: 76,
    height: 76,
    borderRadius: 38,
    textAlign: "center",
    textAlignVertical: "center",
    color: "#fff",
    fontSize: 32,
    fontWeight: "800",
    backgroundColor: "#ffffff22",
  },
  stats: { flexDirection: "row", gap: 6, marginVertical: 11 },
  stat: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 8,
    borderWidth: 1,
    borderColor: "#eceef5",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  statIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#e5f4eb",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  statCopy: { flex: 1, minWidth: 0 },
  muted: { color: "#8a8fa3", fontSize: 11 },
  statCompactLabel: { fontSize: 10 },
  statValue: {
    color: "#1c2030",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 15,
    borderWidth: 1,
    borderColor: "#eceef5",
    marginBottom: 14,
  },
  cardHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  reportCardHead: { alignItems: "center" },
  cardTitle: { color: "#1c2030", fontSize: 17, fontWeight: "700" },
  period: {
    color: PURPLE,
    backgroundColor: "#e5f4eb",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 9,
    fontSize: 11,
  },
  chart: {
    height: 170,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 7,
    marginTop: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#eceef5",
  },
  chartEmpty: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  barGroup: {
    flex: 1,
    height: "100%",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  bar: { width: 17, backgroundColor: "#b7e3c7", borderRadius: 6 },
  barValueWrap: { alignItems: "center", justifyContent: "flex-end" },
  chartValue: {
    color: "#62677b",
    fontSize: 9,
    fontWeight: "700",
    marginBottom: 4,
  },
  barActive: { backgroundColor: PURPLE },
  barLabel: { color: "#8a8fa3", fontSize: 10, marginTop: 7, marginBottom: -20 },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f1f5",
    gap: 11,
  },
  categoryIcon: {
    width: 41,
    height: 41,
    borderRadius: 13,
    backgroundColor: "#e5f4eb",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryInfo: { flex: 1, minWidth: 0 },
  rowTitle: { color: "#1c2030", fontSize: 14, fontWeight: "600" },
  amount: { color: "#1c2030", fontSize: 13, fontWeight: "700" },
  empty: { color: "#8a8fa3", textAlign: "center", paddingVertical: 25 },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 28,
    paddingHorizontal: 18,
  },
  emptyStateCompact: { paddingVertical: 20 },
  emptyStateIcon: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: "#e5f4eb",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyStateTitle: {
    color: "#1c2030",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyStateMessage: {
    color: "#8a8fa3",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    marginTop: 6,
    maxWidth: 280,
  },
  emptyStateAction: {
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: PURPLE,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 14,
    overflow: "hidden",
  },
  emptyStateActionText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  loadMore: {
    alignSelf: "center",
    borderRadius: 10,
    backgroundColor: "#e5f4eb",
    paddingVertical: 9,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  loadMoreText: { color: PURPLE, fontSize: 12, fontWeight: "700" },
  pageIntro: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  sectionTitle: { color: "#1c2030", fontSize: 22, fontWeight: "800" },
  smallPrimary: { backgroundColor: PURPLE, borderRadius: 10, padding: 10 },
  categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  categoryCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: "#eceef5",
  },
  drawerBackdrop: { flex: 1, backgroundColor: "#20223555" },
  drawerOutside: { flex: 1 },
  drawer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 275,
    backgroundColor: "#fff",
    paddingTop: 58,
    paddingHorizontal: 18,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 18,
    elevation: 12,
  },
  drawerBrand: { color: "#1c2030", fontSize: 19, fontWeight: "800" },
  drawerHint: {
    color: "#8a8fa3",
    fontSize: 11,
    marginTop: 3,
    marginBottom: 28,
  },
  drawerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 13,
    paddingHorizontal: 10,
    borderRadius: 11,
  },
  drawerItemActive: { backgroundColor: "#e5f4eb" },
  drawerItemIcon: {
    width: 22,
    color: PURPLE,
    fontSize: 18,
    textAlign: "center",
  },
  chipContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  modalCategoryHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  drawerItemText: { color: "#4e5366", fontSize: 14, fontWeight: "600" },
  drawerDivider: { height: 1, backgroundColor: "#eceef5", marginVertical: 12 },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 73,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#eceef5",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 8,
  },
  navButton: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  navIcon: { color: "#62677b", fontSize: 21 },
  navLabel: { color: "#62677b", fontSize: 11, marginTop: 2 },
  activeText: { color: PURPLE, fontWeight: "700" },
  fab: {
    position: "absolute",
    right: 22,
    bottom: 88,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#1c2030",
    alignItems: "center",
    justifyContent: "center",
    elevation: 8,
  },
  modalBg: {
    flex: 1,
    backgroundColor: "#20223588",
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 25,
    paddingBottom: 35,
  },
  confirmModal: {
    width: "100%",
    borderRadius: 20,
    backgroundColor: "#fff",
    padding: 22,
  },
  confirmTitle: { color: "#1c2030", fontSize: 19, fontWeight: "800" },
  confirmMessage: {
    color: "#62677b",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  confirmActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 22,
  },
  confirmCancel: {
    backgroundColor: "#f0f1f5",
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 16,
  },
  confirmCancelText: { color: "#62677b", fontSize: 13, fontWeight: "700" },
  confirmDelete: {
    backgroundColor: "#df5f65",
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 16,
  },
  confirmDeleteText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  close: {
    position: "absolute",
    top: 10,
    right: 14,
    zIndex: 2,
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: { color: "#8a8fa3", fontSize: 27, lineHeight: 30 },
  modalTitle: {
    fontSize: 23,
    fontWeight: "800",
    color: "#1c2030",
    marginTop: 5,
    marginBottom: 18,
  },
  label: {
    color: "#1c2030",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 10,
    marginBottom: 5,
  },
  optional: { color: "#8a8fa3", fontWeight: "400" },
  input: {
    borderWidth: 1,
    borderColor: "#eceef5",
    borderRadius: 11,
    padding: 12,
    fontSize: 15,
    color: "#1c2030",
  },
  inputError: { borderColor: "#df5f65" },
  inputErrorText: {
    color: "#df5f65",
    fontSize: 11,
    marginTop: 4,
    lineHeight: 16,
  },
  dateButton: {
    borderWidth: 1,
    borderColor: "#eceef5",
    borderRadius: 11,
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateButtonText: { color: "#1c2030", fontSize: 15 },
  doneDate: {
    color: PURPLE,
    textAlign: "right",
    fontWeight: "700",
    marginTop: 8,
  },
  dateNav: { color: PURPLE, fontSize: 30, paddingHorizontal: 10 },
  dateWeek: {
    color: "#72788e",
    fontSize: 10,
    width: "14.285%",
    textAlign: "center",
  },
  dateDay: {
    color: "#1c2030",
    fontSize: 14,
    width: 30,
    height: 30,
    borderRadius: 15,
    textAlign: "center",
    textAlignVertical: "center",
  },
  dateDayActive: { backgroundColor: PURPLE, color: "#fff" },
  iconGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 3 },
  iconChoice: {
    width: 40,
    height: 40,
    borderRadius: 11,
    backgroundColor: "#f7f8fc",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#eceef5",
  },
  iconChoiceActive: { backgroundColor: "#e5f4eb", borderColor: PURPLE },
  iconChoiceText: { fontSize: 22 },
  chips: { flexDirection: "row", marginBottom: 4 },
  subcategorySurface: {
    minHeight: 52,
    backgroundColor: "#f7f8fc",
    borderWidth: 1,
    borderColor: "#eceef5",
    borderRadius: 12,
    paddingHorizontal: 7,
    justifyContent: "center",
    marginBottom: 4,
  },
  subcategorySurfaceContent: {
    alignItems: "center",
    paddingVertical: 5,
  },
  chip: {
    borderWidth: 1,
    borderColor: "#dfe3ed",
    borderRadius: 14,
    backgroundColor: "#fff",
    paddingVertical: 8,
    paddingHorizontal: 11,
    marginRight: 7,
  },
  chipActive: { backgroundColor: "#e5f4eb", borderColor: PURPLE },
  primary: {
    backgroundColor: PURPLE,
    borderRadius: 11,
    padding: 14,
    alignItems: "center",
    marginTop: 18,
  },
  primaryDisabled: { opacity: 0.62 },
  primaryText: { color: "#fff", fontSize: 14, fontWeight: "700" },
  themeToggle: {
    backgroundColor: "#e5f4eb",
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  themeToggleText: { color: PURPLE, fontSize: 12, fontWeight: "700" },
  customSplash: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1000,
    backgroundColor: "#f7f8fc",
  },
  customSplashImage: { width: "100%", height: "100%" },
  onboardingRoot: {
    flex: 1,
    backgroundColor: "#f7f8fc",
    paddingHorizontal: 20,
  },
  onboardingTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
  },
  onboardingBrand: { color: PURPLE, fontSize: 17, fontWeight: "800" },
  onboardingSkip: { color: "#8a8fa3", fontSize: 12, fontWeight: "700" },
  onboardingCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#eceef5",
    padding: 25,
    alignItems: "center",
    marginTop: 88,
    shadowColor: "#172033",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  onboardingIcon: {
    width: 92,
    height: 92,
    borderRadius: 32,
    backgroundColor: "#e5f4eb",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  onboardingTitle: {
    color: "#1c2030",
    fontSize: 24,
    lineHeight: 31,
    fontWeight: "800",
    textAlign: "center",
  },
  onboardingDescription: {
    color: "#62677b",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 11,
    minHeight: 47,
  },
  onboardingDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 27,
    marginBottom: 24,
  },
  onboardingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#d9dce6",
  },
  onboardingDotActive: { width: 22, backgroundColor: PURPLE },
  onboardingButton: {
    width: "100%",
    minHeight: 48,
    borderRadius: 13,
    backgroundColor: PURPLE,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  onboardingButtonText: { color: "#fff", fontSize: 14, fontWeight: "800" },
  onboardingFooter: {
    color: "#8a8fa3",
    textAlign: "center",
    fontSize: 11,
    marginTop: 22,
  },
  featureTourRoot: { flex: 1, backgroundColor: "#00000066" },
  featureTourHighlight: {
    position: "absolute",
    borderWidth: 2,
    borderColor: PURPLE,
    borderRadius: 16,
    backgroundColor: "transparent",
  },
  featureTourArrow: { position: "absolute", zIndex: 4 },
  featureTourConnector: {
    ...StyleSheet.absoluteFill,
    zIndex: 4,
  },
  featureTourBubble: {
    position: "absolute",
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e3e6ef",
    padding: 16,
    shadowColor: "#172033",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  featureTourHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  featureTourIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#e5f4eb",
    alignItems: "center",
    justifyContent: "center",
  },
  featureTourTitle: {
    flex: 1,
    color: "#1c2030",
    fontSize: 15,
    fontWeight: "800",
  },
  featureTourDescription: {
    color: "#62677b",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 11,
  },
  featureTourFooter: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
  },
  featureTourDots: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  featureTourDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#d9dce6",
  },
  featureTourDotActive: { width: 18, backgroundColor: PURPLE },
  featureTourButton: {
    minHeight: 38,
    borderRadius: 11,
    backgroundColor: PURPLE,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  featureTourButtonText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  featureTourSkip: {
    paddingVertical: 8,
    paddingHorizontal: 9,
    marginRight: 4,
  },
  featureTourSkipText: { color: "#7a8095", fontSize: 12, fontWeight: "700" },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  languageToggle: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "#f0f1f5",
    padding: 2,
  },
  languageOption: { borderRadius: 6, paddingVertical: 5, paddingHorizontal: 9 },
  languageOptionActive: { backgroundColor: PURPLE },
  languageOptionText: { color: "#62677b", fontSize: 11, fontWeight: "700" },
  languageOptionActiveText: { color: "#fff" },
  demoDataRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 11,
    backgroundColor: "#f7f8fc",
    borderWidth: 1,
    borderColor: "#eceef5",
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 12,
  },
  demoDataCopy: { flex: 1, minWidth: 0, marginRight: 10 },
});
export const darkStyles = StyleSheet.create({
  safe: { backgroundColor: "#10121a" },
  onboardingRoot: { backgroundColor: "#10121a" },
  onboardingBrand: { color: "#a8e6bd" },
  onboardingSkip: { color: "#a7acc0" },
  onboardingCard: { backgroundColor: "#202536", borderColor: "#343c52" },
  onboardingIcon: { backgroundColor: "#1b5a40" },
  onboardingTitle: { color: "#f2f3f8" },
  onboardingDescription: { color: "#a7acc0" },
  onboardingDot: { backgroundColor: "#454c63" },
  onboardingDotActive: { backgroundColor: "#76dda0" },
  onboardingFooter: { color: "#a7acc0" },
  featureTourRoot: { backgroundColor: "#00000088" },
  featureTourHighlight: { borderColor: "#a8e6bd" },
  featureTourBubble: {
    backgroundColor: DARK_MODAL_SURFACE,
    borderColor: "#3b435a",
  },
  featureTourIcon: { backgroundColor: "#1b5a40" },
  featureTourTitle: { color: "#f2f3f8" },
  featureTourDescription: { color: "#a7acc0" },
  featureTourDot: { backgroundColor: "#454c63" },
  featureTourDotActive: { backgroundColor: "#76dda0" },
  featureTourSkipText: { color: "#f2f3f8" },
  topBar: { backgroundColor: "#171a25", borderBottomColor: "#2b3042" },
  topBarButton: { backgroundColor: DARK_MODAL_SURFACE, borderColor: "#383e55" },
  menuIcon: { color: "#f2f3f8" },
  settingsIcon: { color: "#a8e6bd" },
  appName: { color: "#f2f3f8" },
  appSubtitle: { color: "#a7acc0" },
  card: { backgroundColor: "#202536", borderColor: "#343c52" },
  stat: { backgroundColor: "#202536", borderColor: "#343c52" },
  statIcon: { backgroundColor: "#1b5a40" },
  muted: { color: "#a7acc0" },
  statValue: { color: "#f2f3f8" },
  cardTitle: { color: "#f2f3f8" },
  period: { backgroundColor: "#164b35", color: "#c3f0d2" },
  recentCard: { backgroundColor: "#1b2030", borderColor: "#343c52" },
  reportToggle: { backgroundColor: "#1b2030" },
  reportToggleOptionActive: { backgroundColor: "#1e6245" },
  reportToggleText: { color: "#a7acc0" },
  reportToggleTextActive: { color: "#f2f3f8" },
  reportPeriod: { backgroundColor: "#202536", borderColor: "#343c52" },
  reportPeriodText: { color: "#f2f3f8" },
  reportMetric: { backgroundColor: "#202536", borderColor: "#343c52" },
  reportMetricValue: { color: "#f2f3f8" },
  reportChartContent: { borderBottomColor: "#343c52" },
  reportChartValue: { color: "#d8dbed" },
  reportBarLabel: { color: "#b7bbce" },
  reportBar: { backgroundColor: "#2c9d6b" },
  reportCategoryIcon: { backgroundColor: "#1b5a40" },
  reportCategoryRowActive: { backgroundColor: "#24283a" },
  reportProgressTrack: { backgroundColor: "#343c52" },
  subBreakdown: { borderLeftColor: "#2c9d6b" },
  subBreakdownTitle: { color: "#a8e6bd" },
  subBreakdownName: { color: "#a7acc0" },
  subBreakdownAmount: { color: "#f2f3f8" },
  chart: {
    borderBottomColor: "#343c52",
    backgroundColor: "#1b2030",
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingTop: 8,
  },
  chartValue: { color: "#d8dbed" },
  barLabel: { color: "#b7bbce" },
  bar: { backgroundColor: "#2c9d6b" },
  barActive: { backgroundColor: "#76dda0" },
  row: { borderBottomColor: "#343c52" },
  categoryIcon: { backgroundColor: "#1b5a40" },
  rowTitle: { color: "#f2f3f8" },
  amount: { color: "#f2f3f8" },
  empty: { color: "#a7acc0" },
  emptyState: {},
  emptyStateIcon: { backgroundColor: "#1b5a40" },
  emptyStateTitle: { color: "#f2f3f8" },
  emptyStateMessage: { color: "#a7acc0" },
  emptyStateAction: { backgroundColor: "#2c9d6b" },
  loadMore: { backgroundColor: "#164b35" },
  loadMoreText: { color: "#c3f0d2" },
  categoryCard: { backgroundColor: "#191c28", borderColor: "#2b3042" },
  bottomNav: { backgroundColor: "#171a25", borderTopColor: "#2b3042" },
  navIcon: { color: "#a7acc0" },
  navLabel: { color: "#a7acc0" },
  drawer: { backgroundColor: "#191c28" },
  drawerItem: { backgroundColor: "transparent" },
  drawerBrand: { color: "#f2f3f8" },
  drawerHint: { color: "#a7acc0" },
  drawerItemText: { color: "#f2f3f8" },
  drawerItemIcon: { color: "#a8e6bd" },
  drawerDivider: { backgroundColor: "#2b3042" },
  modalBg: { backgroundColor: "#10121acc" },
  modal: {
    backgroundColor: DARK_MODAL_SURFACE,
    borderWidth: 1,
    borderColor: "#414965",
  },
  confirmModal: {
    backgroundColor: DARK_MODAL_SURFACE,
    borderWidth: 1,
    borderColor: "#414965",
  },
  confirmTitle: { color: "#f2f3f8" },
  confirmMessage: { color: "#a7acc0" },
  confirmCancel: { backgroundColor: "#2b3042" },
  confirmCancelText: { color: "#d7d9e5" },
  eyebrow: { color: "#a8e6bd" },
  modalTitle: { color: "#f2f3f8" },
  label: { color: "#d7d9e5" },
  input: {
    backgroundColor: DARK_MODAL_SURFACE,
    borderColor: "#383e55",
    color: "#f2f3f8",
  },
  inputError: { borderColor: "#ff777d" },
  inputErrorText: { color: "#ff8a8f" },
  dateButton: { backgroundColor: DARK_MODAL_SURFACE, borderColor: "#383e55" },
  dateButtonText: { color: "#f2f3f8" },
  dateIcon: { color: "#f2f3f8" },
  doneDate: { color: "#a8e6bd" },
  dateNav: { color: "#a8e6bd", fontSize: 30, paddingHorizontal: 10 },
  dateWeek: {
    color: "#a7acc0",
    fontSize: 10,
    width: "14.285%",
    textAlign: "center",
  },
  dateDay: {
    color: "#eef0fb",
    fontSize: 14,
    width: 30,
    height: 30,
    borderRadius: 15,
    textAlign: "center",
    textAlignVertical: "center",
  },
  dateDayActive: { backgroundColor: PURPLE, color: "#fff" },
  subcategorySurface: {
    backgroundColor: DARK_MODAL_SURFACE,
    borderColor: "#383e55",
  },
  chip: { backgroundColor: "#30364b", borderColor: "#59627f" },
  chipText: { color: "#edf0fb" },
  chipActive: { backgroundColor: "#164b35", borderColor: "#62d194" },
  optional: { color: "#a7acc0" },
  closeText: { color: "#a7acc0" },
  drawerItemActive: { backgroundColor: "#1e6245" },
  themeToggle: { backgroundColor: "#1e6245" },
  themeToggleText: { color: "#f2f3f8" },
  languageToggle: { backgroundColor: "#2b3042" },
  languageOption: { backgroundColor: "transparent" },
  languageOptionActive: { backgroundColor: "#1e6245" },
  languageOptionText: { color: "#d7d9e5" },
  languageOptionActiveText: { color: "#fff" },
  demoDataRow: { backgroundColor: "#202536", borderColor: "#383e55" },
  fab: { backgroundColor: "#f2f3f8" },
  fabText: { color: "#171a25" },
  fabLabel: { color: "#171a25" },
});
